import com.owners.gravitas.drools.dto.ContactDetails;
 
dialect "mvel"
 
/*
 * This rule checks if it belongs to group 1
 */
rule "Phone Number starts with"
 when
      $contactDetails : ContactDetails(phoneNumber.startsWith( "800" ) ||  phoneNumber.startsWith( "866" ) || phoneNumber.startsWith( "1800" ) || phoneNumber.startsWith( "1866"))          
    then
    	$contactDetails.status = false;
end

rule "Phone Number contains pattern"
    when
      $contactDetails :  ContactDetails(phoneNumber.contains( "111111" ) || phoneNumber.contains( "222222" ) || phoneNumber.contains( "333333" ) || phoneNumber.contains( "444444" ) || phoneNumber.contains( "555555" ) || phoneNumber.contains( "666666" ) || phoneNumber.contains( "777777" ) || phoneNumber.contains( "888888" ) || phoneNumber.contains( "999999" ) || phoneNumber.contains( "000000" ))       
    then
    	$contactDetails.status = false;	
end

